### PR TITLE
Add Meson build definitions.

### PR DESCRIPTION
**Pull request by jpakkane**
This requires a bit more thorough going-over as it has new stuff that might not work:

- The repo itself is very old, hopefully web-integration still works
- the upstream wrap file has a `provide` entry that needs to be properly passed to the end result
- the version number is fairly old, this is on purpose as this is a bit experimental, it can be updated once things work

And ping @legeana just in case notifications are not sent due to the age of the repo.

### CODE REVIEW

**Comment by legeana** [comment]
Hi, could you please add `LICENSE.build`?
There is no explicit `provides` support, but I think it should be a pass-through so it will be fine.

**Comment by jpakkane** [comment]
Added license file.

**Comment by legeana** [comment]
Unfortunately the old implementation is bugged. It doesn't take into account other sections of the ini file.
I am going to fix this.

**Comment by legeana** [comment]
@jpakkane the bug is fixed, this release should be functional now. Anything wraps created before this was fixed are broken if they were using new ini fields.

**Pull request merged**
